# Preprocessing the data for model fitting

In [1]:
import pandas as pd
import pickle
import numpy as np

## Queen's Gambit

In [36]:
# Load the csv data of QG games (October 2020 - March 2021)
direc = '../../Data/Learning/queens_gambit/'

df = pd.concat([pd.read_csv(direc + 'df_{:d}_{:02d}.csv'.format(2020 + j//12,j%12+1),
                            usecols=['black','fourthmove','result'])
                for j in range(9,15)],ignore_index=True)

In [37]:
# Load the pkl data of unique players (March 2020 - September 2020)
players = []
for i in range(3,9):
    with open(direc + 'QG_players_2020_{:02d}.pkl'.format(i),'rb') as f:
        players = pickle.load(f)
s = set(np.array(players).flatten())

# Filter out players who have played the QG in this period
df = df[df['black'].apply(lambda p: not p in s)].reset_index(drop=True)

In [38]:
def get_ordered_unique_values(a):
    x,c = np.unique(a,return_counts=True)
    x = x[np.argsort(c)[::-1]]
    c = np.sort(c)[::-1]
    return x,c

In [39]:
# Add accept (1), decline (either the Slav Defense or QG Declined, 2), other to df
df['fourthcode'] = df['fourthmove'].map({'d5c4' : 1, 'e7e6' : 2, 'c7c6' : 2}).fillna('O')

In [40]:
# Create a binary dataframe of just accept/decline
df_binary = df[(df['fourthcode'].isin([1,2])) & (~df['result'].isna())].reset_index(drop=True)
names,ind = np.unique(df_binary['black'],return_inverse=True)
name_to_ind = dict(zip(names,ind))

df_binary = df_binary.drop('fourthmove', axis=1)

In [41]:
# Map losses to -1 instead of 0 and draws to 0 instead of 0.5
df_binary['result'] = df_binary['result'].map({0.0 : -1, 1.0: 1, 0.5 : 0})

In [42]:
# Change to integers and swap columns
df_binary['result'] = df_binary['result'].astype('Int64')
df_binary['fourthcode'] = df_binary['fourthcode'].astype('Int64')
df_binary = df_binary[['black', 'fourthcode', 'result']]

In [43]:
# Label unique users starting at 1
df_binary['black'] = pd.factorize(df_binary['black'])[0] + 1
df_binary

         black  fourthcode  result
0            1           2       1
1            2           2       1
2            3           2       1
3            4           1      -1
4            3           2       1
...        ...         ...     ...
480927  141931           1      -1
480928  146720           1      -1
480929   16394           1       1
480930  146721           1       1
480931   92243           1      -1

[480932 rows x 3 columns]

In [82]:
# Save to csv
df_binary.to_csv('modeling_QG.csv', index=False)

## Sicilian Defense

In [44]:
# Load the csv data of SD games (October 2020 - March 2021)
direc = '../../Data/Learning/sicilian_defense/'

df = pd.concat([pd.read_csv(direc + 'df_{:d}_{:02d}.csv'.format(2020 + j//12,j%12+1),
                            usecols=['white','thirdmove','result'])
                for j in range(9,15)],ignore_index=True)

In [45]:
# Load the pkl data of unique players (March 2020 - September 2020)
players = []
for i in range(3,9):
    with open(direc + 'SD_players_2020_{:02d}.pkl'.format(i),'rb') as f:
        players = pickle.load(f)
s = set(np.array(players).flatten())

# Filter out players who have played the SD in this period
df = df[df['white'].apply(lambda p: not p in s)].reset_index(drop=True)

In [48]:
# Add closed, open, or else to df
df['thirdcode'] = df['thirdmove'].map({'b1c3' : 1, 'g1f3' : 2}).fillna('E')

In [49]:
# Create a binary dataframe of just closed/open
df_binary = df[(df['thirdcode'].isin([1,2])) & (~df['result'].isna())].reset_index(drop=True)
names,ind = np.unique(df_binary['white'],return_inverse=True)
name_to_ind = dict(zip(names,ind))

df_binary = df_binary.drop('thirdmove', axis=1)

In [51]:
# Map losses to -1 instead of 0 and draws to 0 instead of 0.5
df_binary['result'] = df_binary['result'].map({0.0 : -1, 1.0: 1, 0.5 : 0})

In [52]:
# Change to integers and swap columns
df_binary['result'] = df_binary['result'].astype('Int64')
df_binary['thirdcode'] = df_binary['thirdcode'].astype('Int64')
df_binary = df_binary[['white', 'thirdcode', 'result']]

In [53]:
# Label unique users starting at 1
df_binary['white'] = pd.factorize(df_binary['white'])[0] + 1
df_binary

         white  thirdcode  result
0            1          1       1
1            2          2      -1
2            3          1       1
3            4          2      -1
4            5          2       1
...        ...        ...     ...
714213  113701          2       1
714214  162173          2       1
714215  152889          2       1
714216  162954          2       1
714217   35985          2      -1

[714218 rows x 3 columns]

In [54]:
# Save to csv
df_binary.to_csv('modeling_SD.csv', index=False)

## King's Knight

In [55]:
# Load the csv data of KK games (October 2020 - March 2021)
direc = '../../Data/Learning/kings_knight/'

df = pd.concat([pd.read_csv(direc + 'df_{:d}_{:02d}.csv'.format(2020 + j//12,j%12+1),
                            usecols=['white','fifthmove','result'])
                for j in range(9,15)],ignore_index=True)

In [56]:
# Load the pkl data of unique players (March 2020 - September 2020)
players = []
for i in range(3,9):
    with open(direc + 'KK_players_2020_{:02d}.pkl'.format(i),'rb') as f:
        players = pickle.load(f)
s = set(np.array(players).flatten())

# Filter out players who have played the SD in this period
df = df[df['white'].apply(lambda p: not p in s)].reset_index(drop=True)

In [57]:
# Add italian, ruy lopez, or other to df
df['fifthcode'] = df['fifthmove'].map({'f1c4' : 1, 'f1b5' : 2}).fillna('O')

In [58]:
# Create a binary dataframe of just italian/ruy lopez
df_binary = df[(df['fifthcode'].isin([1, 2])) & (~df['result'].isna())].reset_index(drop=True)
names,ind = np.unique(df_binary['white'],return_inverse=True)
name_to_ind = dict(zip(names,ind))

df_binary = df_binary.drop('fifthmove', axis=1)

In [59]:
# Map losses to -1 instead of 0 and draws to 0 instead of 0.5
df_binary['result'] = df_binary['result'].map({0.0 : -1, 1.0: 1, 0.5 : 0})

In [60]:
# Change to integers and swap columns
df_binary['result'] = df_binary['result'].astype('Int64')
df_binary['fifthcode'] = df_binary['fifthcode'].astype('Int64')
df_binary = df_binary[['white', 'fifthcode', 'result']]

In [61]:
# Label unique users starting at 1
df_binary['white'] = pd.factorize(df_binary['white'])[0] + 1
df_binary

          white  fifthcode  result
0             1          1      -1
1             2          1       1
2             3          2       1
3             4          1      -1
4             5          1       1
...         ...        ...     ...
1225905   95666          1       1
1225906  160799          2      -1
1225907  166225          1       1
1225908  167331          2      -1
1225909  145424          2       1

[1225910 rows x 3 columns]

In [62]:
# Save to csv
df_binary.to_csv('modeling_KK.csv', index=False)

## Caro-Kann Defense

In [63]:
# Load the csv data of CK games (October 2020 - March 2021)
direc = '../../Data/Learning/caro_kann/'

df = pd.concat([pd.read_csv(direc + 'df_{:d}_{:02d}.csv'.format(2020 + j//12,j%12+1),
                            usecols=['white','fifthmove','result'])
                for j in range(9,15)],ignore_index=True)

In [64]:
# Load the pkl data of unique players (March 2020 - September 2020)
players = []
for i in range(3,9):
    with open(direc + 'CK_players_2020_{:02d}.pkl'.format(i),'rb') as f:
        players = pickle.load(f)
s = set(np.array(players).flatten())

# Filter out players who have played the SD in this period
df = df[df['white'].apply(lambda p: not p in s)].reset_index(drop=True)

In [65]:
# Add advance, exchange, or other to df
df['fifthcode'] = df['fifthmove'].map({'e4e5' : 1, 'e4d5' : 2}).fillna('O')

In [66]:
# Create a binary dataframe of just advance/exchange
df_binary = df[(df['fifthcode'].isin([1, 2])) & (~df['result'].isna())].reset_index(drop=True)
names,ind = np.unique(df_binary['white'],return_inverse=True)
name_to_ind = dict(zip(names,ind))

df_binary = df_binary.drop('fifthmove', axis=1)

In [67]:
# Map losses to -1 instead of 0 and draws to 0 instead of 0.5
df_binary['result'] = df_binary['result'].map({0.0 : -1, 1.0: 1, 0.5 : 0})

In [68]:
# Change to integers and swap columns
df_binary['result'] = df_binary['result'].astype('Int64')
df_binary['fifthcode'] = df_binary['fifthcode'].astype('Int64')
df_binary = df_binary[['white', 'fifthcode', 'result']]

In [69]:
# Label unique users starting at 1
df_binary['white'] = pd.factorize(df_binary['white'])[0] + 1
df_binary

       white  fifthcode  result
0          1          1      -1
1          2          2      -1
2          3          1       1
3          4          2       1
4          5          2      -1
...      ...        ...     ...
78718   8946          2      -1
78719  39824          1      -1
78720  25162          2      -1
78721  23638          1      -1
78722  39825          2       0

[78723 rows x 3 columns]

In [70]:
# Save to csv
df_binary.to_csv('modeling_CK.csv', index=False)